CREATE TABLE CLIENTE(
    DNI VARCHAR(9)  PRIMARY KEY,
    NOMBRE VARCHAR(30) NOT NULL,
    UID VARCHAR(30) DEFAULT NULL
);

CREATE TABLE PAGO( 
    DNI VARCHAR(9), 
    Fecha_pago DATE DEFAULT SYSDATE(), 
    Pagado BOOLEAN, 
    PRIMARY KEY(DNI, Fecha_pago), 
    FOREIGN KEY(DNI) REFERENCES CLIENTE(DNI) ON DELETE CASCADE 
);

