CREATE TABLE CLIENTE(
    DNI VARCHAR(9)  PRIMARY KEY,
    NOMBRE VARCHAR(30),
    UID_TARJETA BINARY(4)
);

CREATE TABLE PAGO( 
    DNI VARCHAR(9), 
    Pagado BOOLEAN, 
    PRIMARY KEY(DNI), 
    FOREIGN KEY(DNI) REFERENCES CLIENTE(DNI) ON DELETE CASCADE 
);


INSERT INTO Cliente (dni, nombre, uid_tarjeta) VALUES ('54313742R', 'Juan Miguel', 0xAABCFB3F);
INSERT INTO Pago (dni, pagado) VALUES ('54313742R', 1); 
INSERT INTO Cliente (dni, nombre, uid_tarjeta) VALUES ('54313743W', 'Alvaro', 0xE98E14B4);
INSERT INTO Pago (dni, pagado) VALUES ('54313743W', 0);